server:
  port: 7529
spring:
  cloud:
    gateway:
      default-filters:
        - AddResponseHeader=source, xiaoxin
      routes:
        - id: api_route
          uri: http://localhost:7121
          predicates:
            - Path=/api/**
logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace

dubbo:
  application:
    name: lilemy-api-gateway-consumer
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://localhost:8848